apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: bootsync-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: bootsync-monitoring
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "change-me"
