apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: bootsync-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: bootsync-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: bootsync-app
        metrics_path: /actuator/prometheus
        authorization:
          type: Bearer
          credentials_file: /etc/prometheus/secrets/bootsync-prometheus-token
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - bootsync
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: bootsync-actuator-service
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: http-management

      - job_name: node-exporter
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - bootsync-monitoring
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
