apiVersion: v1
kind: Secret
metadata:
  name: prometheus-scrape-secret
  namespace: bootsync-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: bootsync-monitoring
type: Opaque
stringData:
  bootsync-prometheus-token: "change-me-prometheus-token"
